[model]
# Architecture
input_size_time_series = 5
hidden_size_time_series = 64
num_layers_time_series = 4
dropout = 0.3

vocab_size = 1000
embedding_size = 512
num_heads = 8
num_layers = 6
d_ff = 2048
max_seq_length = 100

[training]
batch_size = 64
num_epochs = 200
learning_rate = 0.0005
lr_scheduler_step = 10
lr_scheduler_gamma = 0.95

[data]
training_tickers = [
	{ ticker = "BBRI.JK", period = "2y" },
	{ ticker = "BMRI.JK", period = "2y" },
	{ ticker = "TLKM.JK", period = "2y" },
	{ ticker = "BBNI.JK", period = "2y" },
	{ ticker = "UNVR.JK", period = "2y" },
	{ ticker = "INDF.JK", period = "2y" },
	{ ticker = "MYOR.JK", period = "2y" },
	{ ticker = "PGAS.JK", period = "2y" },
	{ ticker = "JSMR.JK", period = "2y" },
]
sequence_length = 30
train_test_split = 0.8
features = ["Open", "High", "Low", "Close", "Volume"]

[attention]
hidden_size = 64
num_heads = 1
dropout = 0.2

[prediction]
ticker_symbol = "ASII.JK"
future_days = 64
